In [1]:
%cd drive/My\ Drive

/content/drive/My Drive


In [2]:
%cd case\ studies\ 2

/content/drive/My Drive/case studies 2


In [3]:
!ls

'1-Gathering Data.ipynb'	       'Face Dataset'
'2-Gathering files information.ipynb'   Final_Data
'3-Data Pre-Processing.ipynb'	        Final_Face_Dataset
'4-Gathering Raw Waveforms.ipynb'       mel_spectrograms
'5-Concatenating Raw Waveforms.ipynb'   Models
'Data Augmentation'		        raw_data


In [4]:
%cd raw_data/

/content/drive/My Drive/case studies 2/raw_data


In [5]:
!ls

dev_clean	raw_waveforms  train-clean-100	     validation_file.npy
dev_other	test_clean     training_file.npy     validation_speaker.npy
files_data.npy	test_other     training_speaker.npy


In [0]:
import numpy as np
import pandas as pd
import librosa

In [0]:
import time

In [0]:
pd.set_option('max_colwidth', -1)

In [0]:
files = np.load('files_data.npy', allow_pickle=True)

In [55]:
len(files)

22402

In [56]:
files[0]

'/content/drive/My Drive/case studies 2/raw_data/dev_clean/dev-clean/7850/73752/7850-73752-0008.flac'

In [57]:
df = pd.DataFrame(columns = ['files'])
df['files'] = files
df.head()

files
0  /content/drive/My Drive/case studies 2/raw_data/dev_clean/dev-clean/7850/73752/7850-73752-0008.flac
1  /content/drive/My Drive/case studies 2/raw_data/dev_clean/dev-clean/7850/73752/7850-73752-0019.flac
2  /content/drive/My Drive/case studies 2/raw_data/dev_clean/dev-clean/7850/73752/7850-73752-0015.flac
3  /content/drive/My Drive/case studies 2/raw_data/dev_clean/dev-clean/7850/73752/7850-73752-0009.flac
4  /content/drive/My Drive/case studies 2/raw_data/dev_clean/dev-clean/7850/73752/7850-73752-0006.flac

In [58]:
df['file_name'] = df['files'].str.split('/').str[-1]
df['speaker'] = df['file_name'].str.split('-').str[0]
df.head()

files  ... speaker
0  /content/drive/My Drive/case studies 2/raw_data/dev_clean/dev-clean/7850/73752/7850-73752-0008.flac  ...  7850  
1  /content/drive/My Drive/case studies 2/raw_data/dev_clean/dev-clean/7850/73752/7850-73752-0019.flac  ...  7850  
2  /content/drive/My Drive/case studies 2/raw_data/dev_clean/dev-clean/7850/73752/7850-73752-0015.flac  ...  7850  
3  /content/drive/My Drive/case studies 2/raw_data/dev_clean/dev-clean/7850/73752/7850-73752-0009.flac  ...  7850  
4  /content/drive/My Drive/case studies 2/raw_data/dev_clean/dev-clean/7850/73752/7850-73752-0006.flac  ...  7850  

[5 rows x 3 columns]

In [59]:
len(df)

22402

In [60]:
df.head()

files  ... speaker
0  /content/drive/My Drive/case studies 2/raw_data/dev_clean/dev-clean/7850/73752/7850-73752-0008.flac  ...  7850  
1  /content/drive/My Drive/case studies 2/raw_data/dev_clean/dev-clean/7850/73752/7850-73752-0019.flac  ...  7850  
2  /content/drive/My Drive/case studies 2/raw_data/dev_clean/dev-clean/7850/73752/7850-73752-0015.flac  ...  7850  
3  /content/drive/My Drive/case studies 2/raw_data/dev_clean/dev-clean/7850/73752/7850-73752-0009.flac  ...  7850  
4  /content/drive/My Drive/case studies 2/raw_data/dev_clean/dev-clean/7850/73752/7850-73752-0006.flac  ...  7850  

[5 rows x 3 columns]

In [68]:
mfcc = []
label = []
file_name = []
start = time.time()
for i in range(len(df['files'])):
  try:
    X, sample_rate = librosa.load(df['files'][i], res_type = 'kaiser_fast')
    mfccs = np.mean(librosa.feature.mfcc(y = X, sr = sample_rate, n_mfcc = 40).T, axis = 0)
    mfcc.append(mfccs)
    label.append(df['speaker'][i])
    file_name.append(df['file_name'][i])
    if len(mfcc)%10 == 0:
      print(len(mfcc))
      print(time.time() - start)
  except Exception as e:
    pass

10
2.4558169841766357
20
5.2504942417144775
30
8.23914122581482
40
14.859622716903687
50
20.7008273601532
60
26.59628653526306
70
32.45272469520569
80
39.97944521903992
90
46.570992946624756
100
54.97662305831909
110
62.37615609169006
120
69.88787841796875
130
77.54543399810791
140
85.41830921173096
150
92.04493236541748
160
98.33840107917786
170
103.98764848709106
180
110.60989451408386
190
117.12193393707275
200
124.82439947128296
210
131.53138065338135
220
137.23075246810913
230
145.72145199775696
240
153.53743410110474
250
161.5514018535614
260
167.5930209159851
270
174.7699453830719
280
181.8756217956543
290
188.41391468048096
300
194.9983937740326
310
203.6401915550232
320
210.4480001926422
330
217.7797076702118
340
225.42075610160828
350
232.2917058467865
360
242.94613552093506
370
251.16314053535461
380
260.02801156044006
390
272.776664018631
400
278.09045362472534
410
283.80973505973816
420
289.1383855342865
430
296.67768692970276
440
302.44390964508057
450
308.68645882606506


In [0]:
np.save('mfcc', mfcc, allow_pickle = True)
np.save('label', label, allow_pickle = True)
np.save('file_name', file_name, allow_pickle = True)

In [70]:
len(mfcc)

21820

In [71]:
label[0]

'7850'

In [72]:
df = pd.DataFrame(columns = ['label'])
df['label'] = label
df['label_counts'] = df['label'].map(df['label'].value_counts(dropna = False))
df.head()

label  label_counts
0  7850  72          
1  7850  72          
2  7850  72          
3  7850  72          
4  7850  72

In [73]:
df['label'].nunique()

243

In [74]:
df['label_counts'].max()

155

In [75]:
df['label_counts'].min()

24

In [0]:
df = df.loc[df['label_counts']>=100]

In [80]:
df

label  label_counts
1881   3752  101         
1882   3752  101         
1883   3752  101         
1884   3752  101         
1885   3752  101         
...     ...  ...         
21815  5789  112         
21816  5789  112         
21817  5789  112         
21818  5789  112         
21819  5789  112         

[12593 rows x 2 columns]

In [81]:
label_list = list(df['label'].unique())
label_list = label_list[:100]
present = []
for i in df['label']:
  if i in label_list:
    present.append('yes')
  else:
    present.append('no')
df['present'] = present
df.loc[df['present'] == 'yes']

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':


label  label_counts present
1881   3752  101           yes   
1882   3752  101           yes   
1883   3752  101           yes   
1884   3752  101           yes   
1885   3752  101           yes   
...     ...  ...           ...   
20592  2514  108           yes   
20593  2514  108           yes   
20594  2514  108           yes   
20595  2514  108           yes   
20596  2514  108           yes   

[11451 rows x 3 columns]

In [0]:
df = df.loc[df['present'] == 'yes']

In [0]:
df = df.sort_values('label', ascending = False).groupby('label').head(100)

In [88]:
df

label  label_counts present
19416  909   110           yes   
19422  909   110           yes   
19433  909   110           yes   
19432  909   110           yes   
19431  909   110           yes   
...    ...   ...           ...   
15556  103   102           yes   
15557  103   102           yes   
15558  103   102           yes   
15559  103   102           yes   
15561  103   102           yes   

[10000 rows x 3 columns]

In [0]:
index = list(df.index)
index

In [0]:
final_mfcc = []
final_label = []
final_file_name = []

for i in index:
  final_mfcc.append(mfcc[i])
  final_label.append(label[i])
  final_file_name.append(file_name[i])

In [91]:
len(final_mfcc)

10000

In [92]:
final_mfcc[0].shape

(40,)

In [93]:
final_label[0]

'909'

In [94]:
final_file_name[0]

'909-131044-0014.flac'

In [95]:
%cd ..

/content/drive/My Drive/case studies 2


In [96]:
%cd Models/

/content/drive/My Drive/case studies 2/Models


In [97]:
%cd Voice\ Models

/content/drive/My Drive/case studies 2/Models/Voice Models


In [0]:

import os
os.mkdir('MFCC')

In [0]:
final_mfcc = []
final_label = []
final_file_name = []



In [0]:
np.save('mfcc', final_mfcc, allow_pickle=True)
np.save('label', final_label, allow_pickle=True)
np.save('file_name', final_file_name, allow_pickle=True)

In [0]:
df = pd.DataFrame(columns = ['final_label'])
df['final_label'] = final_label

In [109]:
df

final_label
0     909       
1     909       
2     909       
3     909       
4     909       
...   ...       
9995  103       
9996  103       
9997  103       
9998  103       
9999  103       

[10000 rows x 1 columns]

In [0]:
train_index = list(df.sort_values('final_label', ascending = False).groupby('final_label').head(80).index)
test_index = list(df.sort_values('final_label', ascending = False).groupby('final_label').tail(20).index)

In [0]:
train_mfcc = []
train_label = []
for i in train_index:
  train_mfcc.append(final_mfcc[i])
  train_label.append(final_label[i])

test_mfcc = []
test_label = []
for i in test_index:
  test_mfcc.append(final_mfcc[i])
  test_label.append(final_label[i])

In [113]:
len(train_mfcc)

8000

In [114]:
len(test_mfcc)

2000

In [115]:
len(train_label)

8000

In [116]:
len(test_label)

2000

In [117]:
train_mfcc[0]

array([-3.12488063e+02,  1.40911729e+02, -2.59786946e+01,  5.36977414e+01,
        5.11625367e+00,  1.53814891e+01, -6.37703730e+00, -7.02221034e+00,
       -9.46516455e+00, -1.03866695e+01,  7.27147500e-01, -1.05310579e+01,
        9.99133842e-01, -9.39343456e+00,  2.67762805e+00,  1.80916904e+00,
       -6.10297043e+00,  1.38087904e+00, -3.24361380e+00, -3.06467700e-01,
       -4.19915648e+00, -1.67247241e+00, -2.17762108e+00, -5.07625916e+00,
       -5.53526557e+00, -4.65897698e+00, -3.15326352e+00, -3.99171333e+00,
        3.69127624e-01, -2.59088265e+00, -4.82623714e+00, -3.34075154e+00,
       -1.84578165e+00, -1.71987108e+00, -3.31294975e+00, -3.70248180e+00,
       -2.91824657e+00, -1.95830296e+00, -3.17320953e+00, -2.50416954e+00])

In [118]:
train_label[0]

'909'

In [119]:
test_mfcc[0]

array([-302.64953089,  137.38987784,  -20.07885371,   50.26595353,
         10.48713778,   11.57857957,   -7.17201504,   -2.81766488,
         -8.60608976,  -11.41729439,    1.66559901,   -8.46403257,
         -1.49020819,  -10.72178693,    2.111976  ,    0.60779942,
         -6.16979056,    0.9193667 ,   -4.31497437,   -0.46840825,
         -6.13668932,   -3.33515051,   -2.39379727,   -7.00848707,
         -5.44286589,   -4.73700893,   -3.10394174,   -3.38999459,
         -0.86963291,   -3.09559336,   -5.32294154,   -4.00747979,
         -3.01573755,   -2.92848475,   -2.95739689,   -3.84448235,
         -4.85268413,   -2.81293311,   -2.66255435,   -1.60869576])

In [120]:
test_label[0]

'909'

In [121]:
%cd MFCC/

/content/drive/My Drive/case studies 2/Models/Voice Models/MFCC


In [0]:
np.save('training_data', train_mfcc, allow_pickle=True)
np.save('training_label', train_label, allow_pickle=True)
np.save('test_data', test_mfcc, allow_pickle=True)
np.save('test_label', test_label, allow_pickle=True)

In [123]:
df

final_label
0     909       
1     909       
2     909       
3     909       
4     909       
...   ...       
9995  103       
9996  103       
9997  103       
9998  103       
9999  103       

[10000 rows x 1 columns]

In [0]:
df = df.sample(frac = 1)

In [125]:
df

final_label
3702  5688      
2115  7067      
9649  116       
6070  3983      
4409  5163      
...    ...      
3088  6415      
6616  3660      
7876  2843      
7772  2989      
1351  7902      

[10000 rows x 1 columns]

In [0]:
train_index = list(df.sort_values('final_label', ascending = False).groupby('final_label').head(80).index)
test_index = list(df.sort_values('final_label', ascending = False).groupby('final_label').tail(20).index)

In [0]:
train_mfcc = []
train_label = []
for i in train_index:
  train_mfcc.append(final_mfcc[i])
  train_label.append(final_label[i])

test_mfcc = []
test_label = []
for i in test_index:
  test_mfcc.append(final_mfcc[i])
  test_label.append(final_label[i])

In [0]:
np.save('training_data', train_mfcc, allow_pickle=True)
np.save('training_label', train_label, allow_pickle=True)
np.save('test_data', test_mfcc, allow_pickle=True)
np.save('test_label', test_label, allow_pickle=True)

In [132]:
!ls

test_data.npy  test_label.npy  training_data.npy  training_label.npy


In [130]:
!pwd

/content/drive/My Drive/case studies 2/Models/Voice Models/MFCC


In [0]:
train_df = pd.DataFrame(columns = ['train_label'])
train_df['train_label'] = train_label
train_df = train_df.sample(frac = 1)
train_index = list(train_df.index)
final_train_mfcc = []
final_train_label = []

for i in train_index:
  final_train_mfcc.append(train_mfcc[i])
  final_train_label.append(train_label[i])

In [135]:
len(final_train_mfcc)

8000

In [136]:
final_train_mfcc[0]

array([-3.51633361e+02,  1.04243890e+02, -3.36392980e+01,  5.84098323e+01,
       -2.57855330e+01,  2.23461594e+01, -7.89129548e+00,  4.21778564e+00,
        4.63949055e+00,  2.20570022e+00,  8.67200072e+00, -5.63492051e+00,
        1.21083566e+01,  4.19578443e+00,  9.37915991e+00, -3.36409905e-01,
        5.91336137e+00,  2.62223840e+00,  6.65672848e-01,  3.81478879e+00,
        6.60927113e-01,  6.43315508e+00, -3.04569197e-01,  6.19189450e+00,
        3.51948326e+00,  4.19591538e+00,  3.87887698e+00,  3.31723307e+00,
        3.99260367e+00,  2.58989333e+00,  5.76212540e+00,  2.84128852e+00,
        5.37113041e+00,  4.97051912e+00,  3.91604057e+00,  3.99498196e+00,
        4.70059605e+00,  3.00513785e+00,  3.67548147e+00,  3.64935673e+00])

In [0]:
final_train_label

In [0]:
test_df = pd.DataFrame(columns = ['test_label'])
test_df['test_label'] = test_label
test_df = test_df.sample(frac = 1)
test_index = list(test_df.index)
final_test_mfcc = []
final_test_label = []

for i in test_index:
  final_test_mfcc.append(test_mfcc[i])
  final_test_label.append(test_label[i])

In [139]:
final_test_mfcc[0]

array([-3.79206582e+02,  8.81701831e+01, -3.40488497e+01,  5.39215722e+01,
        1.87510673e+00,  9.52634652e+00, -1.27902925e+01, -6.69799813e+00,
       -1.83407986e+00, -8.38440831e-01,  5.44649554e+00, -6.67406131e+00,
        1.08147982e+01,  1.24507711e+00,  3.89491744e+00,  2.92849479e+00,
       -1.26343231e+00,  1.63738010e+00, -1.50335322e+00,  3.27483350e+00,
       -2.19217754e+00,  8.67520848e-01,  3.68056495e+00,  1.41321214e+00,
        1.47106200e+00,  3.54145114e+00,  4.44859244e+00,  2.50240612e+00,
        2.85499982e+00,  1.51517437e+00,  1.14078628e+00,  1.38979504e+00,
        1.29436907e+00, -3.09398226e-01,  5.90717806e-01,  1.27000911e+00,
        1.03787893e+00,  1.51320083e+00, -4.12762901e-01, -1.27800236e+00])

In [140]:
len(final_test_mfcc)

2000

In [141]:
len(final_test_label)

2000

In [0]:
final_test_label

In [0]:
np.save('test_data', final_test_mfcc, allow_pickle=True)
np.save('test_label', final_test_label, allow_pickle=True)
np.save('train_data', final_train_mfcc, allow_pickle=True)
np.save('train_label', final_train_label, allow_pickle=True)